<?php $collection = $this->loadDataByUserId(); ?>

<table class="data-table">
    <thead>
    <tr>
        <th>Product ID</th>
        <th>Product Name</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($collection as $item): ?>
        <tr>
            <td><?php echo $item->getProductId(); ?></td>
            <td><?php echo $this->loadProductNameById((int)($item->getProductId())); ?></td>
            <td>
                <form action="<?php echo $this->removeButtonAction((int)$item->getSubscribeId()) ?>" method="post"
                <div class="actions">
                    <button type="submit"
                            title="submit"
                            class="button"><span><span> Usuń </span></span></button>
                </div>
                </form>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>