<?php $_product = $this->getProduct(); ?>

<?php if (($_product->isAvailable()) !== false): ?>
    <?php return; ?>
<?php endif; ?>

<?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
    <?php if ($this->checkIfSubscriptionExists() !== 0): ?>
        <?php echo $this->__('Product is already subscribed') ?>
        <?php return; ?>
    <?php endif; ?>

    <form action="<?php echo $this->getFormUserAction() ?>" method="post" id="newsletter-validate-detail">
        <div class="block-content">
            <div class="form-subscribe-header">
                <label><?php echo $this->__('Notify me when this products is back in stock') ?></label>
            </div>
            <div class="actions">
                <button type="submit"
                        class="button"><span><span><?php echo $this->__('Subscribe') ?></span></span></button>
            </div>
        </div>
    </form>

<?php else: ?>

    <?php if ($this->getRequest()->getParam('email') !== NULL): ?>
        <?php $email = $this->getRequest()->getParam('email'); ?>
        <?php echo $email.$this->__(' already subscribes this product'); ?>
        <?php return; ?>
    <?php endif; ?>

    <form action="<?php echo $this->getFormAnonymousAction() ?>" method="post"
          id="subscriber-email-validate">
        <div class="block-content">
            <div class="form-subscribe-header">
                <label><?php echo $this->__('Notify me when this products is back in stock') ?></label>
            </div>
            <div class="input-box">
                <input type="email" name="email" id="productsubscription"
                       placeholder="<?php echo $this->__('Your email address') ?>"
                       title="email"
                       class="input-text required-entry validate-email"/>
            </div>
            <div class="actions">
                <button type="submit"
                        title="submit"
                        class="button"><span><span><?php echo $this->__('Subscribe') ?></span></span></button>
            </div>
        </div>
    </form>

<?php endif; ?>
<script type="text/javascript">
    var newsletterSubscriberFormDetail = new VarienForm('subscriber-email-validate');
</script>